// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWyDqYIuyBz-Gzb-dpo7hO96-Lp39pm-0',
    appId: '1:172286231999:web:0fbab658074d65ef634d0a',
    messagingSenderId: '172286231999',
    projectId: 'uni-lecture-app',
    authDomain: 'uni-lecture-app.firebaseapp.com',
    storageBucket: 'uni-lecture-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0mo0jl336Y3EnwCqXguUZGm4ITMBjpQw',
    appId: '1:172286231999:android:22139e4954ee65cc634d0a',
    messagingSenderId: '172286231999',
    projectId: 'uni-lecture-app',
    storageBucket: 'uni-lecture-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpIUEnHdf6NDvZ2D-8Zosl3j-SkICKxCY',
    appId: '1:172286231999:ios:d0befc53c30d11d0634d0a',
    messagingSenderId: '172286231999',
    projectId: 'uni-lecture-app',
    storageBucket: 'uni-lecture-app.appspot.com',
    iosBundleId: 'com.example.uniLecture',
  );
}
